### ISSUE TITLE
false positive detection

### ISSUE THREAD

**Issue by robsongajunior** [incodenz/bot-detect#1]
## DESCRIPTION OF UNEXPECTED BEHAVIOR

Using `Chrome` on localhost in a simple page, it is bot flag.

![Screen Shot 2019-10-18 at 16 39 39](https://user-images.githubusercontent.com/3317013/67123925-e2f4f100-f1c7-11e9-8008-f125abcf3425.png)

**Comment by aalfiann** [comment]
your second console.log is executed first, because onUser event is run as asynchronous .

**Comment by robsongajunior** [comment]
You are right.

I wait 5/10 seconds and onUser was not performed.
But, the problem is... The isBot flag is true, but should not because was a valid chrome browser.

Did work good for you?

**Comment by xsilent-cleopatra** [comment]
No no no, this library is not to detect your browser are valid or not, but to detect are you a real human or not.  

The way this library works is to make a challenge test for your visitor. To make sure it is valid user or not, you have to move your mouse or touch the view port screen when on mobile view. Actualy Bot can not do this. Then, if there is any user event detected, isBot flag will change to false.

This is not false positif detection, because the default value for `isBot` flag is true.

About your question, did this work good for you? Yes, this work well for me.. I use this library to detect bot in my website. See my [website](https://imgreader.netlify.com/view/?content=24%3DpzblLmcmN2914tczb2LWpGxlFtcleGci9WRlJlYtZ3L2lGVyFzdvbWc3QXRlNoLhcmc2V3Jl5uLpYWbGZ2Fh9tLuY2bnQnRlNvblcmdXNHVil0auZ2YXcy9yM6L0cHaHR). and please test my website by using this application >> [https://try-puppeteer.appspot.com/](https://try-puppeteer.appspot.com/)

Note:
- Today bot can use headless browser like PhantomJS, Selenium, Puppeteer or CasperJS which is based on chrome or webdriver. You can not detect them by browser fingerprint only, there must be having challenge test too.

**Comment by aalfiann** [comment]
@robsongajunior , setTimeout will not working because you have to send event click or event mouse move.

**Comment by robsongajunior** [comment]
Aaaaaah, ok...
... I had wrong understood, sorry about that.


@xsilent-cleopatra thanks. Now I understand the behavior expected.

> o make sure it is valid user or not, you have to move your mouse or touch the view port screen when on mobile view. Actualy Bot can not do this. Then, if there is any user event detected, isBot flag will change to false.

Thanks.

@aalfiann aaah, sure. Now, it is clear for me. Thanks very much.

> closing the issue
